site_name: GMS Tutorials
site_description: Groundwater Modeling System Tutorials

# Theme
theme:
  name: readthedocs

# Navigation
nav:
  - Home: index.md
  - MODFLOW:
    - Grid Approach: modflow/grid/MODFLOW-GridApproach.md

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
